key_names = {
    'KEY_ESCAPE': 'esc',
    'KEY_RETURN': 'return',
    'KEY_ENTER': 'enter',
    'KEY_DELETE': 'delete',
    'KEY_CTRL': 'ctrl',
    'KEY_CONTROL': 'ctrl',
    'KEY_ALT': 'alt',
    'KEY_OPTION': 'alt',
    'KEY_LEFT_ARROW': 'left',
    'KEY_LEFT': 'left',
    'KEY_RIGHT_ARROW': 'right',
    'KEY_RIGHT': 'right',
    'KEY_UP_ARROW': 'up',
    'KEY_UP': 'up',
    'KEY_DOWN_ARROW': 'down',
    'KEY_DOWN': 'down',
    'KEY_SPACE_BAR': 'space',
    'KEY_SPACEBAR': 'space',
    'KEY_SPACE': 'space',
    'KEY_BACKSPACE': 'backspace',
    'KEY_TAB': 'tab',

    'KEY_SCROLL_LOCK': 'scroll lock',
    'KEY_PRINT_SCREEN': 'print screen',
    'KEY_INSERT': 'insert',
    'KEY_PAUSE': 'pause',
    'KEY_CAPS_LOCK': 'caps lock',
    'KEY_CAPSLOCK': 'caps lock',
    'KEY_NUMBER_LOCK': 'num lock',
    'KEY_NUMBERLOCK': 'num lock',
    'KEY_NUM_LOCK': 'num lock',
    'KEY_NUMLOCK': 'num lock',
    'KEY_PAGE_UP': 'page up',
    'KEY_PAGEUP': 'page up',
    'KEY_PAGE_DOWN': 'page down',
    'KEY_PAGEDOWN': 'page down',

    'KEY_A': 'A',
    'KEY_B': 'B',
    'KEY_C': 'C',
    'KEY_D': 'D',
    'KEY_E': 'E',
    'KEY_F': 'F',
    'KEY_G': 'G',
    'KEY_H': 'H',
    'KEY_I': 'I',
    'KEY_J': 'J',
    'KEY_K': 'K',
    'KEY_L': 'L',
    'KEY_M': 'M',
    'KEY_N': 'N',
    'KEY_O': 'O',
    'KEY_P': 'P',
    'KEY_Q': 'Q',
    'KEY_R': 'R',
    'KEY_S': 'S',
    'KEY_T': 'T',
    'KEY_U': 'U',
    'KEY_V': 'V',
    'KEY_W': 'W',
    'KEY_X': 'X',
    'KEY_Y': 'Y',
    'KEY_Z': 'Z',
    'KEY_a': 'a',
    'KEY_b': 'b',
    'KEY_c': 'c',
    'KEY_d': 'd',
    'KEY_e': 'e',
    'KEY_f': 'f',
    'KEY_g': 'g',
    'KEY_h': 'h',
    'KEY_i': 'i',
    'KEY_j': 'j',
    'KEY_k': 'k',
    'KEY_l': 'l',
    'KEY_m': 'm',
    'KEY_n': 'n',
    'KEY_o': 'o',
    'KEY_p': 'p',
    'KEY_q': 'q',
    'KEY_r': 'r',
    'KEY_s': 's',
    'KEY_t': 't',
    'KEY_u': 'u',
    'KEY_v': 'v',
    'KEY_w': 'w',
    'KEY_x': 'x',
    'KEY_y': 'y',
    'KEY_z': 'z',

    'KEY_0': '0',
    'KEY_1': '1',
    'KEY_2': '2',
    'KEY_3': '3',
    'KEY_4': '4',
    'KEY_5': '5',
    'KEY_6': '6',
    'KEY_7': '7',
    'KEY_8': '8',
    'KEY_9': '9',
}
